/* The TalkerOS "5 Card Draw Poker" Plugin - HEADER FILE
   ------------------------------------------------------------- */

#define plugin_01x000_POKERFILE "pokerdata"
#define plugin_01x000_GAME_NAME_LEN 12
struct plugin_01x000_po_player {
  int hand[5];
  int putin;
  int touched;
  int rank;
  struct plugin_01x000_po_player_hist *hist;
  struct user_struct *user;
  struct plugin_01x000_po_game *game;
  struct plugin_01x000_po_player *prev, *next;
};
struct plugin_01x000_po_game {
 char name[plugin_01x000_GAME_NAME_LEN+1];
  struct room_struct *room;
  struct plugin_01x000_po_player *players;
  struct plugin_01x000_po_player *dealer;
  struct plugin_01x000_po_player *opened;
  int num_players;
  int num_raises;
  int in_players;
  int newdealer;
  int deck[52];
  int top_card;  
  int state;
  int bet;
  int pot;
  struct plugin_01x000_po_player *curr_player, *first_player, *last_player;
  struct plugin_01x000_po_game *prev, *next;
};
struct plugin_01x000_po_game *plugin_01x000_po_game_first, *plugin_01x000_po_game_last;
struct plugin_01x000_po_player_hist {
  char name[USER_NAME_LEN+1];
  int total;
  int given;
};

struct plugin_01x000_po_player_hist *plugin_01x000_po_hist[50];
int plugin_01x000_max_po_hist;
/******* Cards **********/  
  
#define plugin_01x000_CARD_LENGTH 5
#define plugin_01x000_CARD_WIDTH  5
  
static char *plugin_01x000_cards[52][plugin_01x000_CARD_LENGTH]={
  {".---.",
   "|~OL2~RS  |",
   "| ~OLC~RS |",
   "|  ~OL2~RS|",
   "`---'"},
  {".---.",
   "|~OL3~RS  |",
   "| ~OLC~RS |",
   "|  ~OL3~RS|",
   "`---'"},
  {".---.",
   "|~OL4~RS  |",
   "| ~OLC~RS |",
   "|  ~OL4~RS|",
   "`---'"},
  {".---.",
   "|~OL5~RS  |",
   "| ~OLC~RS |",
   "|  ~OL5~RS|",
   "`---'"},
  {".---.",
   "|~OL6~RS  |",
   "| ~OLC~RS |",
   "|  ~OL6~RS|",
   "`---'"},
  {".---.",
   "|~OL7~RS  |",
   "| ~OLC~RS |",
   "|  ~OL7~RS|",
   "`---'"},
  {".---.",
   "|~OL8~RS  |",
   "| ~OLC~RS |",
   "|  ~OL8~RS|",
   "`---'"},
  {".---.",
   "|~OL9~RS  |",
   "| ~OLC~RS |",
   "|  ~OL9~RS|",
   "`---'"},
  {".---.",
   "|~OL10~RS |",
   "| ~OLC~RS |",
   "| ~OL10~RS|",
   "`---'"},
  {".---.",
   "|~OLJ~RS  |",
   "| ~OLC~RS |",
   "|  ~OLJ~RS|",
   "`---'"},
  {".---.",
   "|~OLQ~RS  |",
   "| ~OLC~RS |",
   "|  ~OLQ~RS|",
   "`---'"},
  {".---.",
   "|~OLK~RS  |",
   "| ~OLC~RS |",
   "|  ~OLK~RS|",
   "`---'"},
  {".---.",
   "|~OLA~RS  |",
   "| ~OLC~RS |",
   "|  ~OLA~RS|",
   "`---'"},
   
  {".---.",
   "|~FR2~RS  |",
   "| ~FRd~RS |",
   "|  ~FR2~RS|",
   "`---'"},
  {".---.",
   "|~FR3~RS  |",
   "| ~FRd~RS |",
   "|  ~FR3~RS|",
   "`---'"},
  {".---.",
   "|~FR4~RS  |",
   "| ~FRd~RS |",
   "|  ~FR4~RS|",
   "`---'"},
  {".---.",
   "|~FR5~RS  |",
   "| ~FRd~RS |",
   "|  ~FR5~RS|",
   "`---'"},
  {".---.",
   "|~FR6~RS  |",
   "| ~FRd~RS |",
   "|  ~FR6~RS|",
   "`---'"},
  {".---.",
   "|~FR7~RS  |",
   "| ~FRd~RS |",
   "|  ~FR7~RS|",
   "`---'"},
  {".---.",
   "|~FR8~RS  |",
   "| ~FRd~RS |",
   "|  ~FR8~RS|",
   "`---'"},
  {".---.",
   "|~FR9~RS  |",
   "| ~FRd~RS |",
   "|  ~FR9~RS|",
   "`---'"},
  {".---.",
   "|~FR10~RS |",
   "| ~FRd~RS |",
   "| ~FR10~RS|",
   "`---'"},
  {".---.",
   "|~FRJ~RS  |",
   "| ~FRd~RS |",
   "|  ~FRJ~RS|",
   "`---'"},
  {".---.",
   "|~FRQ~RS  |",
   "| ~FRd~RS |",
   "|  ~FRQ~RS|",
   "`---'"},
  {".---.",
   "|~FRK~RS  |",
   "| ~FRd~RS |",
   "|  ~FRK~RS|",
   "`---'"},
  {".---.",
   "|~FRA~RS  |",
   "| ~FRd~RS |",
   "|  ~FRA~RS|",
   "`---'"},
  {".---.",
   "|~FR2~RS  |",
   "| ~FRh~RS |",
   "|  ~FR2~RS|",
   "`---'"},
  {".---.",
   "|~FR3~RS  |",
   "| ~FRh~RS |",
   "|  ~FR3~RS|",
   "`---'"},
  {".---.",
   "|~FR4~RS  |",
   "| ~FRh~RS |",
   "|  ~FR4~RS|",
   "`---'"},
  {".---.",
   "|~FR5~RS  |",
   "| ~FRh~RS |",
   "|  ~FR5~RS|",
   "`---'"},
  {".---.",
   "|~FR6~RS  |",
   "| ~FRh~RS |",
   "|  ~FR6~RS|",
   "`---'"},
  {".---.",
   "|~FR7~RS  |",
   "| ~FRh~RS |",
   "|  ~FR7~RS|",
   "`---'"},
  {".---.",
   "|~FR8~RS  |",
   "| ~FRh~RS |",
   "|  ~FR8~RS|",
   "`---'"},
  {".---.",
   "|~FR9~RS  |",
   "| ~FRh~RS |",
   "|  ~FR9~RS|",
   "`---'"},
  {".---.",
   "|~FR10~RS |",
   "| ~FRh~RS |",
   "| ~FR10~RS|",
   "`---'"},
  {".---.",
   "|~FRJ~RS  |",
   "| ~FRh~RS |",
   "|  ~FRJ~RS|",
   "`---'"},
  {".---.",
   "|~FRQ~RS  |",
   "| ~FRh~RS |",
   "|  ~FRQ~RS|",
   "`---'"},
  {".---.",
   "|~FRK~RS  |",
   "| ~FRh~RS |",
   "|  ~FRK~RS|",
   "`---'"},
  {".---.",
   "|~FRA~RS  |",
   "| ~FRh~RS |",
   "|  ~FRA~RS|",
   "`---'"},
   
  {".---.",
   "|~OL2~RS  |",
   "| ~OLS~RS |",
   "|  ~OL2~RS|",
   "`---'"},
  {".---.",
   "|~OL3~RS  |",
   "| ~OLS~RS |",
   "|  ~OL3~RS|",
   "`---'"},
  {".---.",
   "|~OL4~RS  |",
   "| ~OLS~RS |",
   "|  ~OL4~RS|",
   "`---'"},
  {".---.",
   "|~OL5~RS  |",
   "| ~OLS~RS |",
   "|  ~OL5~RS|",
   "`---'"},
  {".---.",
   "|~OL6~RS  |",
   "| ~OLS~RS |",
   "|  ~OL6~RS|",
   "`---'"},
  {".---.",
   "|~OL7~RS  |",
   "| ~OLS~RS |",
   "|  ~OL7~RS|",
   "`---'"},
  {".---.",
   "|~OL8~RS  |",
   "| ~OLS~RS |",
   "|  ~OL8~RS|",
   "`---'"},
  {".---.",
   "|~OL9~RS  |",
   "| ~OLS~RS |",
   "|  ~OL9~RS|",
   "`---'"},
  {".---.",
   "|~OL10~RS |",
   "| ~OLS~RS |",
   "| ~OL10~RS|",
   "`---'"},
  {".---.",
   "|~OLJ~RS  |",
   "| ~OLS~RS |",
   "|  ~OLJ~RS|",
   "`---'"},
  {".---.",
   "|~OLQ~RS  |",
   "| ~OLS~RS |",
   "|  ~OLQ~RS|",
   "`---'"},
  {".---.",
   "|~OLK~RS  |",
   "| ~OLS~RS |",
   "|  ~OLK~RS|",
   "`---'"},
  {".---.",
   "|~OLA~RS  |",
   "| ~OLS~RS |",
   "|  ~OLA~RS|",
   "`---'"}
};
